---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
---
spring:
  profiles: subject
words: Yo,Tu,El,Ella,Eso

---
spring:
  profiles: verb
words: correr,sabia,tenia,sierra,compro

---
spring:
  profiles: article
words: un,la

---
spring:
  profiles: adjective
words: razonable,agujereado,suspicaz,ordinario,improbable

---
spring:
  profiles: noun
words: bote,libro,votar,asiento,mochila,dividir,la marmota
