---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: subject
words: subject

---
spring:
  profiles: verb
words: verb

---
spring:
  profiles: article
words: article

---
spring:
  profiles: adjective
words: adjective

---
spring:
  profiles: noun
words: noun

